name: Publish custom-image

on:
  push:
    tags:
      - "*"

  release:
    types: [released]

jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code-server
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get and set VERSION
        run: |
          TAG="${{ github.event.inputs.version || github.ref_name }}"
          echo "VERSION=${TAG#v}" >> $GITHUB_ENV

      - name: Download release artifacts
        uses: robinraju/release-downloader@v1.7
        with:
          repository: "coder/code-server"
          tag: v4.11.0
          fileName: "*.deb"
          out-file-path: "release-packages"

      - name: Publish to Docker
        run: ./ci/steps/docker-buildx-push.sh
        env:
          VERSION: ${{ env.VERSION }}
          GITHUB_TOKEN: ${{ github.token }}
          DOCKER_REGISTRY: docker.io/ashish155/codeserver
          

